import os
import json
import requests

BASE_URL = os.getenv("SERVICE_URL", "http://localhost:8000")

sample_html = """
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Test PDF</title>
    <style>
      body { font-family: DejaVu Sans, Arial, sans-serif; margin: 40px; }
      h1 { color: #2e7d32; }
      .box { border: 1px solid #ccc; padding: 12px; border-radius: 8px; }
    </style>
  </head>
  <body>
    <h1>HTML to PDF Test</h1>
    <p>This PDF was generated by the HTMLtoPDF service.</p>
    <div class="box">Hello, Render + n8n!</div>
  </body>
</html>
"""

payload = {
    "html": sample_html,
    "filename": "sample.pdf",
    "options": {
        "page-size": "A4",
        "margin-top": "10mm",
        "margin-right": "10mm",
        "margin-bottom": "10mm",
        "margin-left": "10mm",
    },
}

resp = requests.post(f"{BASE_URL}/convert", json=payload)
print("Status:", resp.status_code)
print("Content-Type:", resp.headers.get("Content-Type"))

if resp.status_code == 200 and resp.headers.get("Content-Type") == "application/pdf":
    with open("output.pdf", "wb") as f:
        f.write(resp.content)
    print("Saved output.pdf")
else:
    try:
        print(resp.json())
    except Exception:
        print(resp.text)
